version: '3.3'

services:
   client:
    restart: on-failure
    ports:
      - $PORT_CLIENT:80
    image: 'uwcirg/tb-mobile-app:dockerized-v1'
    environment:
      URL_API: $URL_API
      CONTACT_LINK: $CONTACT_LINK
      URL_MESSAGE_API: $URL_MESSAGE_API

  db:
    restart: always
    image: postgres

  web:
    image: kjgoodwins/foundation:production
    environment:
      - DATA=postgres://postgres:postgres@db
      - PASSWORD
      - PORT=3000
      - RAILS_ENV=development
      - URL_API=$URL_API
      - URL_CORS=$URL_CORS
      - WA_KEY=$WA_KEY
      - WA_SID=$WA_SID
      - VAPID_PUBLIC_KEY=$VAPID_PUBLIC_KEY
      - VAPID_PRIVATE_KEY=$VAPID_PRIVATE_KEY
    ports:
      - $PORT_API:3000
    depends_on:
      - db
    restart: always
    volumes:
      - source: user-documents
        target: /ruby/backend/upload/
        type: volume
    
      

  mongo:
    expose:
      - "27017"
    container_name: mongo
    image: "mongo"
    restart: always

  message:
    container_name: "message"
    depends_on:
      - mongo
    image: kjgoodwins/message
    ports:
      - "$PORT_MESSAGE:5002"
    environment:
      PORT: "5002"
      MDPORT: "mongo:27017"
      NAME: "message"
    restart: always

volumes:
    user-documents: {}
